### PR TITLE
Restructure code and update README for NEURON-CoreNEURON workflow

### PR DESCRIPTION
**Pull request by pramodk**
Michael : Some members from OIST asked about brief document/tutorial for using CoreNEURON. As we don't have concrete document yet, I thought it would be good idea to update this `ringtest` as an example to show the complete workflow. I have done following modifications : 

* split `ringtest.py` into smaller bits (all functionality remains same)
* Update READM with instructions for
  * downloading and building NEURON, CoreNEURON and MOD2c
  * running ringtest with NEURON
  * resuming simulation with CoreNEURON
  * sample bash script to do above (on standard linux system) 
* Some additional details about benchmarking/common errors

There are some todo sections that you can update.

Let me know what you think.

### CODE REVIEW

**Comment by pramodk** [comment]
And then we can add link to this repository in CoreNEURON and mod2c github pages.

**Comment by pramodk** [comment]
forgot to mention that the scripts and old instructions are moved to `scripts` directory.

**Comment by nrnhines** [comment]
Hi Pramod,
Rather than accept a merge, I selected for the changesets to be rebased onto the 
master so that the extra merge commit was avoided. Perhaps with the 5 related commits
it would have been better to make the graph clear that they were together. My question
is whether the rebase causes any extra effort on your side. If so, from now on I'll accept
the merge style.

I'm working mostly on the grant application this month. In looking at the changes I did 
notice a few typos and things I would like to change. However they are minor and can 
be done later. It is nice to have a much more complete explanation about getting started.

Cheers,
Michael

**Comment by pramodk** [comment]
> My question is whether the rebase causes any extra effort on your side.

No.

Rebase is fine for merging such feature branches (except some scenarios described as [Golden Rule of Rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing#the-golden-rule-of-rebasing)).

For modifications from this type of pull request, I would prefer `squashing` all commits into single commit while merging (as [described here](https://github.com/blog/2141-squash-your-commits)).

> However they are minor and can be done later. It is nice to have a much more complete explanation about getting started.

I will update the README  with more information.

**Pull request merged**
